name: 'Terraform Single-Branch Workflow'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (staging or production)'
        required: true
        default: 'staging'

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set AWS credentials based on the environment
      - name: Set AWS credentials
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION_PROD }}" >> $GITHUB_ENV
          else
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_STG }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}" >> $GITHUB_ENV
            echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION_STG }}" >> $GITHUB_ENV
          fi

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check

      # Step 5: Terraform Validation
      - name: Terraform Validation
        run: terraform validate

      # Step 6: Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -out=plan-${{ github.event.inputs.environment }}.tfplan

      # Step 7: Manual Approval for Production
      - name: Await Manual Approval
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Apply Terraform Changes
      - name: Terraform Apply
        if: ${{ github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production' }}
        run: terraform apply -auto-approve plan-${{ github.event.inputs.environment }}.tfplan

      # Step 9: Notify Success
      - name: Notify Success
        if: success()
        run: |
          aws sns publish --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
            --message "Terraform Apply succeeded for ${{ github.event.inputs.environment }} environment!" \
            --subject "Terraform Apply Success"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
